version: "3.6"
services:
  api:
    build: .
    depends_on:
      - redis-database
    ports:
      - "5000:5000"
    networks:
      - sharedNet

  redis-database:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - sharedNet

networks:
  sharedNet:
    driver: bridge
