version: "3.9"
services:
  redis-db:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379
    networks:
      - sharedNet

  mongo-db:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - sharedNet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo-db
    networks:
      - sharedNet

  catalog:
    container_name: catalog-api
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://mongo:27017/catalog
    build:
      context: ./catalog
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - sharedNet
    restart: unless-stopped
    depends_on:
      - mongo-db

  cart:
    container_name: cart-api
    environment:
      PORT: 3001
      DATABASE_URL: mongodb://mongo:27017/catalog
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - sharedNet
    restart: unless-stopped
    depends_on:
      - mongo-db

  gateway:
    container_name: gateway-gql
    environment:
      PORT: 4000
      CATALOG_URL: http://catalog-api:3000/api/v1/catalog/
      CART_URL: http://cart-api:3001/api/v1/
      ORDER_URL: http://order-api:3002/api/v2/order
      SECRET: sometihngsecret
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - sharedNet
    restart: unless-stopped
    depends_on:
      - catalog
      - cart
      - redis-db

volumes:
  mongo-volume:
  redis-volume:


networks:
  sharedNet:
    driver: bridge
